#include "BoomBapClassicAlgebraGenerator.h"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <set>

namespace bbg { namespace {
constexpr int barTicks=64;
int tick(const BoomBapClassicAlgebraNote& n){ return ((n.tick64%barTicks)+barTicks)%barTicks; }
bool has(const BoomBapClassicAlgebraPattern& p,int lane,int bar,int t){ return std::any_of(p.notesByLane[lane].begin(),p.notesByLane[lane].end(),[&](const auto& n){return n.barIndex==bar&&tick(n)==t;}); }
int count(const BoomBapClassicAlgebraPattern& p,int lane){return (int)p.notesByLane[lane].size();}
float close(int v,int ideal,int tolerance){return std::clamp(1.0f-std::abs(v-ideal)/(float)std::max(1,tolerance),0.0f,1.0f);}
float band(float x,float low,float high,float tolerance){if(x>=low&&x<=high)return 1;float d=x<low?low-x:x-high;return static_cast<float>(std::exp(-std::pow(d/std::max(.001f,tolerance),2)));}
enum Family{Kick,Snare,Hats,Ghost,Perc,Families};
Family family(int lane){if(lane==BoomBapClassicLanes::Kick)return Kick;if(lane==BoomBapClassicLanes::Snare)return Snare;if(lane<=BoomBapClassicLanes::OpenHat||lane==BoomBapClassicLanes::Ride)return Hats;if(lane==BoomBapClassicLanes::ClapGhost||lane==BoomBapClassicLanes::KickGhost)return Ghost;return Perc;}
float onsetSimilarity(const BoomBapClassicAlgebraPattern& p,int a,int b,const BoomBapStyleProfile& profile){float inter=0,uni=0;for(int lane=0;lane<BoomBapClassicLanes::Count;++lane){if(lane==BoomBapClassicLanes::Sub808)continue;std::set<int>x,y;for(const auto&n:p.notesByLane[lane]){if(n.barIndex==a)x.insert(tick(n));if(n.barIndex==b)y.insert(tick(n));}std::vector<int>both;std::set_intersection(x.begin(),x.end(),y.begin(),y.end(),std::back_inserter(both));std::set<int>either=x;either.insert(y.begin(),y.end());float w=profile.similarity.familyWeights[family(lane)];inter+=w*both.size();uni+=w*either.size();}return uni>0?inter/uni:1;}
float variance(const std::vector<float>&v){if(v.size()<2)return 0;float m=std::accumulate(v.begin(),v.end(),0.0f)/v.size(),s=0;for(float x:v)s+=(x-m)*(x-m);return s/v.size();}
struct FastRun{int longest=0,repeatedBars=0,notes=0;float velocityVariance=0,occupancy=0;};
FastRun fastRun(const BoomBapClassicAlgebraPattern&p){FastRun f;std::array<int,16>perBar{};std::vector<float>vel;for(int lane:{BoomBapClassicLanes::HiHat,BoomBapClassicLanes::HatAccent}){auto n=p.notesByLane[lane];std::sort(n.begin(),n.end(),[](auto&a,auto&b){return a.tick64<b.tick64;});f.notes+=(int)n.size();int run=0;for(size_t i=1;i<n.size();++i){int d=n[i].tick64-n[i-1].tick64;run=d<=2?run+1:0;f.longest=std::max(f.longest,run);vel.push_back((float)n[i].velocity);if(d<=2&&n[i].barIndex>=0&&n[i].barIndex<16)++perBar[n[i].barIndex];}}f.repeatedBars=(int)std::count_if(perBar.begin(),perBar.end(),[](int n){return n>=2;});f.velocityVariance=variance(vel);f.occupancy=std::clamp(f.notes/64.0f,0.0f,1.0f);return f;}
float velocityScore(const std::vector<BoomBapClassicAlgebraNote>&n){std::vector<float>v;for(auto&x:n)v.push_back((float)x.velocity);return std::clamp(std::sqrt(variance(v))/18.0f,0.0f,1.0f);}
} // namespace

BoomBapClassicScoreBreakdown BoomBapClassicPatternScorer::score(const BoomBapClassicAlgebraPattern&p,const BoomBapClassicAlgebraParams&params,const BoomBapStyleProfile&profile)const{
 BoomBapClassicScoreBreakdown o;int bars=std::max(1,params.bars),back=0;float metric=0;for(int b=0;b<bars;++b){back+=has(p,BoomBapClassicLanes::Snare,b,16)+has(p,BoomBapClassicLanes::Snare,b,48);float s=has(p,BoomBapClassicLanes::Kick,b,0)?1.0f:0.0f;s+=(has(p,BoomBapClassicLanes::Kick,b,4)||has(p,BoomBapClassicLanes::Kick,b,60))?.55f:0;s+=has(p,BoomBapClassicLanes::HiHat,b,0)?.25f:0;metric+=std::min(1.0f,s);}o.backbeatScore=back/(float)(bars*2);o.kickAnchorScore=metric/bars;
 // Kick count: a band, not a single target - played loops spread over 3-5 kicks a bar (calibration
 // split: 3 19 %, 4 38 %, 5 26 %), a peaked target made every candidate converge on one count
 // (docs/audit/BOOMBAP_STAGE.md, step 3).
 int kicks=count(p,BoomBapClassicLanes::Kick),hats=count(p,BoomBapClassicLanes::HiHat)+count(p,BoomBapClassicLanes::HatAccent),ghosts=count(p,BoomBapClassicLanes::ClapGhost)+count(p,BoomBapClassicLanes::KickGhost);o.grooveScore=.5f*band(kicks/(float)bars,3.0f+params.density*.8f,4.0f+params.density*1.0f,.75f)+.35f*close(hats,bars*8+(int)(params.density*bars*3),bars*4)+.15f*close(ghosts,(int)(params.density*bars*1.5f),bars*2);
 int sync=0;for(auto&n:p.notesByLane[BoomBapClassicLanes::Kick])sync+=tick(n)%16!=0;float syncRatio=kicks?sync/(float)kicks:0,dropout=std::clamp(1-hats/(float)(bars*12),0.0f,1.0f);o.breakResemblanceScore=std::clamp(.45f*o.backbeatScore+.25f*band(syncRatio,.25f,.70f,.25f)+.15f*band(dropout,.1f,.55f,.25f)+.15f*o.kickAnchorScore,0.0f,1.0f);
 int comparisons=0;float vs=0;if(bars>=2){o.similarity12=onsetSimilarity(p,0,1,profile);vs+=band(o.similarity12,profile.similarity.confirmationLow,profile.similarity.confirmationHigh,profile.similarity.tolerance);++comparisons;}if(bars>=3){o.similarity13=onsetSimilarity(p,0,2,profile);vs+=band(o.similarity13,profile.similarity.developmentLow,profile.similarity.developmentHigh,profile.similarity.tolerance);++comparisons;}if(bars>=4){o.similarity14=onsetSimilarity(p,0,3,profile);vs+=band(o.similarity14,profile.similarity.turnaroundLow,profile.similarity.turnaroundHigh,profile.similarity.tolerance);++comparisons;}o.variationScore=comparisons?vs/comparisons:.75f;
 auto notes=p.allNotes();int total=(int)notes.size(),plausible=0,early=0,over=0;for(auto&n:notes){plausible+=std::abs(n.timing.pocketPPQ)<=20&&std::abs(n.timing.humanJitterPPQ)<=5;early+=n.laneIndex==BoomBapClassicLanes::Snare&&n.timing.total()<0;over+=std::abs(n.timing.humanJitterPPQ)>5;}o.microPlausibilityScore=total?plausible/(float)total:1;o.earlySnarePenalty=early/(float)std::max(1,bars*2);o.overHumanizePenalty=over/(float)std::max(1,total);o.densityBalanceScore=close(total,bars*(10+(int)(params.density*6)),bars*8);o.velocityHumanityScore=.65f*velocityScore(p.notesByLane[BoomBapClassicLanes::HiHat])+.35f*velocityScore(notes);o.negativeSpaceScore=std::clamp(1-total/(float)(bars*40),0.0f,1.0f);
 int sub=count(p,BoomBapClassicLanes::Sub808);o.lowEndDisciplineScore=sub==0?1:std::clamp(1-(sub-1)*.5f,0.0f,1.0f);o.sub808OverusePenalty=std::clamp(std::max(0,sub-std::max(1,bars/4))*.35f,0.0f,1.0f);auto f=fastRun(p);o.trapLeakConfidence=std::clamp(.45f*std::clamp(f.longest/5.0f,0.0f,1.0f)+.3f*std::clamp(f.repeatedBars/3.0f,0.0f,1.0f)+.15f*(f.velocityVariance<12?1.0f:0.0f)+.1f*f.occupancy,0.0f,1.0f);o.hardTrapLeak=o.trapLeakConfidence>.8f&&f.longest>=4&&f.repeatedBars>=2;o.trapLeakPenalty=o.trapLeakConfidence<.25f?0:(o.trapLeakConfidence-.25f)/.75f;if(sub&&params.substyle==BoomBapSubstyle::Classic)o.trapLeakPenalty+=.6f;o.conflictPenalty=0;for(int b=0;b<bars;++b)for(int t:{16,48})o.conflictPenalty+=has(p,BoomBapClassicLanes::Kick,b,t)?.25f:0;o.spamPenalty=std::clamp(std::max(0,kicks-bars*5)*.25f+std::max(0,hats-bars*13)*.08f,0.0f,2.0f);
 int contextualGhosts=0,validGhostVelocity=0;for(const auto&n:p.notesByLane[BoomBapClassicLanes::ClapGhost]){const bool contextual=n.role==BoomBapClassicRole::FillSupport||n.role==BoomBapClassicRole::ClapLayer||(n.anchorLane==BoomBapClassicLanes::Snare&&n.anchorTick64>=0);contextualGhosts+=contextual;if(n.anchorLane==BoomBapClassicLanes::Snare){auto anchor=std::find_if(p.notesByLane[BoomBapClassicLanes::Snare].begin(),p.notesByLane[BoomBapClassicLanes::Snare].end(),[&](const auto&a){return a.tick64==n.anchorTick64;});validGhostVelocity+=anchor!=p.notesByLane[BoomBapClassicLanes::Snare].end()&&n.velocity<anchor->velocity;}else validGhostVelocity+=n.role==BoomBapClassicRole::FillSupport;}
 const int snareGhosts=count(p,BoomBapClassicLanes::ClapGhost);o.ghostContextQuality=snareGhosts?contextualGhosts/(float)snareGhosts:1.0f;o.ghostVelocityQuality=snareGhosts?validGhostVelocity/(float)snareGhosts:1.0f;
 int relationalKicks=0;for(const auto&n:p.notesByLane[BoomBapClassicLanes::Kick])relationalKicks+=n.role==BoomBapClassicRole::Anchor||n.role==BoomBapClassicRole::Syncopated||n.role==BoomBapClassicRole::Response||n.role==BoomBapClassicRole::Turnaround;for(const auto&n:p.notesByLane[BoomBapClassicLanes::KickGhost])relationalKicks+=n.anchorLane==BoomBapClassicLanes::Kick;o.kickConversationQuality=std::clamp(relationalKicks/(float)std::max(1,kicks+count(p,BoomBapClassicLanes::KickGhost)),0.0f,1.0f);
 o.hatMotifCoherence=bars>=4?std::clamp((o.similarity12*.50f+o.similarity13*.30f+o.similarity14*.20f)/.82f,0.0f,1.0f):o.variationScore;
 if(p.realizedEvent!=RarePhraseEvent::None){const bool dropoutEvent=p.realizedEvent==RarePhraseEvent::HatDropout||p.realizedEvent==RarePhraseEvent::BreakStop;o.dropoutQuality=dropoutEvent?std::clamp(o.negativeSpaceScore+.25f,0.0f,1.0f):0;o.fillQuality=p.realizedEvent==RarePhraseEvent::SnareFill?std::clamp(.45f*o.velocityHumanityScore+.35f*(1-o.trapLeakConfidence)+.20f*o.backbeatScore,0.0f,1.0f):0;o.rareEventQuality=std::max({o.fillQuality,o.dropoutQuality,.72f*(1-o.trapLeakConfidence)});}else o.rareEventQuality=1.0f;
 const float archetypeNovelty=p.context.archetype==BoomBapGrooveArchetype::Pocket?0.15f:p.context.archetype==BoomBapGrooveArchetype::BreakHeavy?.55f:p.context.archetype==BoomBapGrooveArchetype::Sparse?.65f:p.context.archetype==BoomBapGrooveArchetype::Syncopated?.72f:.78f;o.novelty=std::clamp(.45f*archetypeNovelty+.30f*(p.realizedEvent!=RarePhraseEvent::None?1.0f:0.0f)+.25f*band(syncRatio,.35f,.70f,.25f),0.0f,1.0f);
 auto&w=profile.scorer;o.quality=w.backbeat*o.backbeatScore+w.metricSupport*o.kickAnchorScore+w.groove*o.grooveScore+w.breakResemblance*o.breakResemblanceScore+w.microPlausibility*o.microPlausibilityScore+w.negativeSpace*o.negativeSpaceScore+w.lowEnd*o.lowEndDisciplineScore+w.variation*o.variationScore+w.density*o.densityBalanceScore+w.velocity*o.velocityHumanityScore+.22f*o.ghostContextQuality+.15f*o.ghostVelocityQuality+.18f*o.kickConversationQuality+.12f*o.hatMotifCoherence+.10f*o.rareEventQuality-w.trapLeak*o.trapLeakPenalty-w.earlySnare*o.earlySnarePenalty-w.overHumanize*o.overHumanizePenalty-w.sub808*o.sub808OverusePenalty-w.conflict*o.conflictPenalty-w.spam*o.spamPenalty-(o.hardTrapLeak?2.0f:0.0f);return o;
}
} // namespace bbg
